/**
 * SharkDB - Structured Shark Database
 * Sourced from: Wikipedia, Shark Research Institute (SRI), and World Wildlife Fund (WWF)
 */

window.SHARK_DATABASE = [
  {
    id: "great-white",
    name: "Great White Shark",
    scientificName: "Carcharodon carcharias",
    avgSizeM: 4.5,
    maxSizeM: 6.1,
    maxWeightKg: 2268,
    maxSpeedKmh: 40,
    threatLevel: "High",
    threatReason: "Responsible for the largest number of recorded unprovoked attacks, primarily due to mistaking humans for seals in low-visibility water. However, attacks are extremely rare and usually non-fatal 'test bites'.",
    habitats: ["Open Ocean", "Coastal Waters", "Temperate Seas"],
    depthRangeM: "0 - 1200m",
    diet: "Seals, sea lions, dolphins, large fish, carrion",
    conservationStatus: "Vulnerable",
    conservationDetails: "Protected globally, but populations are declining due to commercial fishing, bycatch in gill nets, and habitat degradation. Heavily highlighted in WWF conservation programs.",
    description: "The Great White Shark is the world's largest known predatory fish. It is a highly adapted apex predator, utilizing countershading (grey top, white belly) for camouflage and a highly sensitive sense of smell and electroreception.",
    behavior: "Active during the day, Great White Sharks are solitary hunters known for 'breaching'—leaping completely out of the water to ambush seals from below.",
    coolFact: "Great Whites have a special heat-exchanging circulatory system (rete mirabile) that keeps their body temperature warmer than the surrounding cold ocean, allowing them to remain active in near-freezing waters.",
    sources: ["Wikipedia - Great White Shark", "Shark Research Institute (SRI)", "WWF Species Directory"]
  },
  {
    id: "tiger-shark",
    name: "Tiger Shark",
    scientificName: "Galeocerdo cuvier",
    avgSizeM: 3.5,
    maxSizeM: 5.5,
    maxWeightKg: 900,
    maxSpeedKmh: 32,
    threatLevel: "High",
    threatReason: "As generalist scavengers, they are curious and less selective about their prey. They are considered the second most dangerous shark to humans in terms of recorded bites.",
    habitats: ["Tropical Waters", "Subtropical Waters", "Coastal Reefs"],
    depthRangeM: "0 - 350m",
    diet: "Fish, sea turtles, birds, squid, other sharks, marine mammals, carrion, and debris",
    conservationStatus: "Near Threatened",
    conservationDetails: "Frequently caught in commercial longlines and targeted for their high-quality fins, skin, and liver oil. WWF monitors their trade under CITES regulations.",
    description: "Known as the 'wastebasket of the sea' due to their opportunistic feeding habits, Tiger Sharks are recognizable by the dark stripes running down their bodies, which fade as they mature.",
    behavior: "Typically solitary and nocturnal hunters. They are migratory, traveling thousands of miles to warm waters during winter months.",
    coolFact: "Tiger Sharks have incredibly saw-like teeth that can crack open the hard shells of adult sea turtles and clams with ease.",
    sources: ["Wikipedia - Tiger Shark", "Shark Research Institute (SRI) Database", "WWF Marine Portal"]
  },
  {
    id: "bull-shark",
    name: "Bull Shark",
    scientificName: "Carcharhinus leucas",
    avgSizeM: 2.4,
    maxSizeM: 3.3,
    maxWeightKg: 315,
    maxSpeedKmh: 40,
    threatLevel: "High",
    threatReason: "They inhabit shallow coastal waters and frequently swim up freshwater rivers (near human populations), making accidental encounters more likely. Extremely territorial and aggressive.",
    habitats: ["Estuaries", "Freshwater Rivers", "Coastal Warm Waters"],
    depthRangeM: "0 - 150m",
    diet: "Fish, other sharks, dolphins, terrestrial animals that fall into rivers",
    conservationStatus: "Vulnerable",
    conservationDetails: "Particularly vulnerable to human impact because of their coastal and riverine habitats, which suffer from heavy pollution and development.",
    description: "The Bull Shark is famous for its unique physiological ability to tolerate freshwater. It is a stocky, muscular predator with a short, blunt snout and an aggressive nature.",
    behavior: "Agile and aggressive hunters in turbid, shallow waters. They use a bump-and-bite technique to assess and subdue their prey.",
    coolFact: "Bull Sharks possess specialized kidneys and rectal glands that adapt to filter out salt, enabling them to live in Lake Nicaragua and travel thousands of miles up the Mississippi and Amazon rivers.",
    sources: ["Wikipedia - Bull Shark", "Shark Research Institute (SRI)", "WWF Wildlife Conservation"]
  },
  {
    id: "great-hammerhead",
    name: "Great Hammerhead Shark",
    scientificName: "Sphyrna mokarran",
    avgSizeM: 4.0,
    maxSizeM: 6.1,
    maxWeightKg: 580,
    maxSpeedKmh: 40,
    threatLevel: "Medium",
    threatReason: "Due to their massive size, they are potentially dangerous, but unprovoked attacks on humans are exceptionally rare. Usually shy or indifferent to divers.",
    habitats: ["Open Ocean", "Coastal Warm Waters", "Coral Reefs"],
    depthRangeM: "0 - 300m",
    diet: "Stingrays, fish, squid, crabs, smaller sharks",
    conservationStatus: "Critically Endangered",
    conservationDetails: "Severely threatened by overfishing. Their large fins are highly prized in Asian markets, making them a primary target of illegal finning. Strongly protected under CITES Appendix II.",
    description: "The largest of the hammerhead species, distinguished by its tall, sickle-shaped dorsal fin and wide, straight-edged cephalofoil (hammer-shaped head).",
    behavior: "Often solitary and nomadic. They use their wide heads to pin stingrays to the sea floor before consuming them.",
    coolFact: "The hammer shape of their head acts like a wing, giving them extreme maneuverability, and houses a massive array of electroreceptors to find buried prey.",
    sources: ["Wikipedia - Great Hammerhead", "Shark Research Institute (SRI) Red List", "WWF Endangered Species"]
  },
  {
    id: "whale-shark",
    name: "Whale Shark",
    scientificName: "Rhincodon typus",
    avgSizeM: 10.0,
    maxSizeM: 18.8,
    maxWeightKg: 19000,
    maxSpeedKmh: 5,
    threatLevel: "Low",
    threatReason: "Completely harmless to humans. They are gentle filter feeders that pose no threat. Divers frequently swim alongside them.",
    habitats: ["Tropical Oceans", "Warm Temperate Seas", "Open Ocean"],
    depthRangeM: "0 - 1900m",
    diet: "Plankton, krill, small fish, fish eggs",
    conservationStatus: "Endangered",
    conservationDetails: "Threatened by vessel strikes, marine pollution, entanglement in fishing nets, and unregulated tourism. WWF leads global monitoring programs to track their migration.",
    description: "The Whale Shark is the largest fish species on Earth. It has a distinctive pattern of white spots and stripes on a dark grey back, unique to each individual like a human fingerprint.",
    behavior: "Slow-moving, docile, and highly migratory. They filter feed by sucking water into their massive mouths while swimming close to the surface.",
    coolFact: "A Whale Shark's mouth can be up to 1.5 meters wide and contains over 300 rows of tiny, non-functional teeth.",
    sources: ["Wikipedia - Whale Shark", "Shark Research Institute (SRI)", "WWF Marine Species Protection"]
  },
  {
    id: "shortfin-mako",
    name: "Shortfin Mako Shark",
    scientificName: "Isurus oxyrinchus",
    avgSizeM: 3.2,
    maxSizeM: 4.5,
    maxWeightKg: 506,
    maxSpeedKmh: 74,
    threatLevel: "Medium",
    threatReason: "Extremely fast and powerful. They have bitten humans when hooked or provoked, but rarely target swimmers unprovoked.",
    habitats: ["Open Ocean", "Temperate Waters", "Tropical Waters"],
    depthRangeM: "0 - 740m",
    diet: "Tuna, swordfish, mackerel, squid, other sharks",
    conservationStatus: "Endangered",
    conservationDetails: "Declining rapidly due to target sportfishing and commercial longlining bycatch. Listed under CITES Appendix II to restrict international trade.",
    description: "The Shortfin Mako is the fastest shark in the world, built for high-speed pursuit. It has a sleek, hydrodynamic torpedo-shaped body, indigo-blue coloration, and large, dark eyes.",
    behavior: "Highly active, pelagic predator. Makos are famous for their acrobatic leaps, jumping up to 9 meters (30 feet) out of the water.",
    coolFact: "Like the Great White, the Mako has a countercurrent heat exchange system, allowing it to maintain muscle temperatures up to 8°C warmer than the surrounding water.",
    sources: ["Wikipedia - Shortfin Mako", "Shark Research Institute (SRI)", "WWF Fisheries Program"]
  },
  {
    id: "basking-shark",
    name: "Basking Shark",
    scientificName: "Cetorhinus maximus",
    avgSizeM: 8.0,
    maxSizeM: 12.2,
    maxWeightKg: 5200,
    maxSpeedKmh: 6,
    threatLevel: "Low",
    threatReason: "Harmless filter feeders. Pose no danger to humans, though their rough skin can cause abrasions if touched.",
    habitats: ["Cold Seas", "Temperate Coastal Waters", "Open Ocean"],
    depthRangeM: "0 - 1200m",
    diet: "Zooplankton, tiny fish, invertebrate larvae",
    conservationStatus: "Endangered",
    conservationDetails: "Severely depleted historically by hunting for liver oil, food, and fins. Populations are slow to recover. Protected under WWF and CITES programs.",
    description: "The second-largest living fish species. They are slow-moving and are named for their habit of 'basking' at the surface of the water, filtering plankton with wide-open mouths.",
    behavior: "Social animals that sometimes migrate in schools. They filter feed passively using specialized gill rakers to trap tiny organisms.",
    coolFact: "Basking Sharks can filter up to 2,000 tons of seawater per hour through their enormous gill slits.",
    sources: ["Wikipedia - Basking Shark", "Shark Research Institute (SRI)", "WWF UK Marine Conservation"]
  },
  {
    id: "greenland-shark",
    name: "Greenland Shark",
    scientificName: "Somniosus microcephalus",
    avgSizeM: 4.5,
    maxSizeM: 7.3,
    maxWeightKg: 1200,
    maxSpeedKmh: 2.6,
    threatLevel: "Low",
    threatReason: "Live in extremely cold, deep Arctic waters. Zero recorded attacks on humans, as their habitat does not overlap with swimmers.",
    habitats: ["Arctic Ocean", "Deep Cold Waters", "Boreal Seas"],
    depthRangeM: "0 - 2200m",
    diet: "Fish, seals, carrion (including moose and polar bears that drown)",
    conservationStatus: "Vulnerable",
    conservationDetails: "Primarily threatened by climate change (warming Arctic waters) and bycatch in deep-sea trawling. Their slow growth rates make recovery difficult.",
    description: "A sluggish, slow-moving deep-sea shark. They possess a high concentration of toxic compounds (trimethylamine oxide) in their tissues to survive the intense pressure and cold.",
    behavior: "Extremely slow swimmers, matching the slow metabolic rates required by their freezing environments. Often scavenge dead animals.",
    coolFact: "The Greenland Shark is the longest-living vertebrate on Earth, estimated to live between 250 and 500 years. They do not reach sexual maturity until around 150 years of age.",
    sources: ["Wikipedia - Greenland Shark", "Shark Research Institute (SRI) Research", "WWF Arctic Programme"]
  },
  {
    id: "nurse-shark",
    name: "Nurse Shark",
    scientificName: "Ginglymostoma cirratum",
    avgSizeM: 2.4,
    maxSizeM: 3.1,
    maxWeightKg: 120,
    maxSpeedKmh: 12,
    threatLevel: "Low",
    threatReason: "Generally docile and sedentary. Will bite if stepped on, grabbed, or provoked by divers, but attacks are never fatal and are easily avoided.",
    habitats: ["Shallow Coral Reefs", "Mangrove Channels", "Sandy Flats"],
    depthRangeM: "0 - 130m",
    diet: "Lobsters, crabs, sea urchins, squid, small fish",
    conservationStatus: "Vulnerable",
    conservationDetails: "Vulnerable to coastal habitat destruction (coral reefs and mangroves) and local overfishing. IUCN lists their status as Vulnerable in several regions.",
    description: "A bottom-dwelling shark with a broad, flat head, sensory barbels near the nostrils (used to search the sand for food), and a brown coloration.",
    behavior: "Nocturnal hunters that spend the daytime resting in piles or huddles on the sandy sea floor or in underwater caves.",
    coolFact: "Nurse Sharks use 'suction feeding' to extract prey from tight crevices, generating enough pressure to suck snails right out of their shells.",
    sources: ["Wikipedia - Nurse Shark", "Shark Research Institute (SRI)", "WWF Oceans"]
  },
  {
    id: "blue-shark",
    name: "Blue Shark",
    scientificName: "Prionace glauca",
    avgSizeM: 3.1,
    maxSizeM: 3.8,
    maxWeightKg: 206,
    maxSpeedKmh: 35,
    threatLevel: "Medium",
    threatReason: "Open ocean sharks that are curious and have occasionally bitten shipwreck survivors or divers, but encounters are extremely rare.",
    habitats: ["Deep Ocean", "Temperate Waters", "Tropical Waters"],
    depthRangeM: "0 - 350m",
    diet: "Squid, schooling fish, small sharks, seabirds",
    conservationStatus: "Near Threatened",
    conservationDetails: "The most heavily fished shark in the world, primarily caught as bycatch in tuna and swordfish longlines. Estimated millions killed annually.",
    description: "An elegant, slender pelagic shark with long pectoral fins and a striking deep indigo-blue color on top, fading to bright blue on the sides and white underneath.",
    behavior: "Highly migratory, travelling in large groups sorted by sex and size. They can migrate across entire ocean basins.",
    coolFact: "Blue Sharks are exceptionally prolific, giving birth to litters of up to 130 pups after a gestation period of about 9 to 12 months.",
    sources: ["Wikipedia - Blue Shark", "Shark Research Institute (SRI)", "WWF Bycatch Mitigation Projects"]
  },
  {
    id: "thresher-shark",
    name: "Common Thresher Shark",
    scientificName: "Alopias vulpinus",
    avgSizeM: 4.5,
    maxSizeM: 6.1,
    maxWeightKg: 340,
    maxSpeedKmh: 48,
    threatLevel: "Low",
    threatReason: "Extremely shy and evasive. Their mouths are small and they avoid human contact entirely. No fatalities recorded.",
    habitats: ["Open Ocean", "Coastal Waters", "Temperate Seas"],
    depthRangeM: "0 - 500m",
    diet: "Anchovies, sardines, mackerel, squid",
    conservationStatus: "Vulnerable",
    conservationDetails: "Threatened by sport fishing and target longlines for their meat and fins. Highly sensitive to population decline due to low reproductive rates.",
    description: "Instantly recognizable by their enormous scythe-like caudal (tail) fin, which can be as long as the rest of the shark's body combined.",
    behavior: "Solitary hunters that swim at high speeds. They use their long tail like a whip to stun and corral schools of fish.",
    coolFact: "A Thresher Shark whips its tail at speeds up to 80 km/h (50 mph) to create a shockwave, incapacitating multiple fish at once before eating them.",
    sources: ["Wikipedia - Thresher Shark", "Shark Research Institute (SRI)", "WWF Sustainable Seafood"]
  },
  {
    id: "lemon-shark",
    name: "Lemon Shark",
    scientificName: "Negaprion brevirostris",
    avgSizeM: 2.7,
    maxSizeM: 3.4,
    maxWeightKg: 180,
    maxSpeedKmh: 28,
    threatLevel: "Low",
    threatReason: "Non-aggressive toward humans. No fatal bites have ever been recorded, though they can defend themselves if handled or cornered.",
    habitats: ["Mangrove Swamps", "Shallow Estuaries", "Sandy Reefs"],
    depthRangeM: "0 - 90m",
    diet: "Bony fish, crustaceans, stingrays",
    conservationStatus: "Vulnerable",
    conservationDetails: "Particularly threatened by the destruction of shallow mangrove nursery grounds. Listed under CITES to control commercial export.",
    description: "Named for its yellowish-brown skin color, which helps it blend into the sandy, sun-drenched bottoms of shallow tropical waters. It has two dorsal fins of equal size.",
    behavior: "Known to be social and cooperative. Young lemon sharks spend their first few years in shallow nurseries, showing a high level of site fidelity.",
    coolFact: "Lemon Sharks are one of the most studied shark species in the world, demonstrating high intelligence, social structures, and the ability to learn from one another.",
    sources: ["Wikipedia - Lemon Shark", "Shark Research Institute (SRI) Studies", "WWF Habitat Protection"]
  },
  {
    id: "sand-tiger-shark",
    name: "Sand Tiger Shark",
    scientificName: "Carcharias taurus",
    avgSizeM: 2.5,
    maxSizeM: 3.2,
    maxWeightKg: 159,
    maxSpeedKmh: 15,
    threatLevel: "Low",
    threatReason: "Despite their ferocious look (exposed, jagged teeth), they are docile and slow-moving. They only bite humans defensively if provoked or spearfishing.",
    habitats: ["Coastal Reefs", "Underwater Caves", "Sandy Bays"],
    depthRangeM: "0 - 190m",
    diet: "Small fish, squid, crabs, smaller sharks",
    conservationStatus: "Critically Endangered",
    conservationDetails: "Declined severely due to historic overfishing and low reproduction. They are highly protected in the US, Australia, and South Africa. Main focus of WWF reef conservation.",
    description: "Also known as the Grey Nurse Shark, it has a bulky body, light brown back with dark spots, and characteristic protruding spike-like teeth.",
    behavior: "Slow-moving nocturnal hunters. Often seen hovering completely motionless in the water, especially inside shipwrecks and caves.",
    coolFact: "The Sand Tiger is the only shark known to gulp air from the surface and store it in its stomach, using it as an adjustable ballast to hover weightlessly.",
    sources: ["Wikipedia - Sand Tiger Shark", "Shark Research Institute (SRI)", "WWF Endangered Habitats"]
  },
  {
    id: "blacktip-reef",
    name: "Blacktip Reef Shark",
    scientificName: "Carcharhinus melanopterus",
    avgSizeM: 1.2,
    maxSizeM: 1.8,
    maxWeightKg: 14,
    maxSpeedKmh: 30,
    threatLevel: "Low",
    threatReason: "Very small and skittish. Will flee from swimmers, but has occasionally nipped the ankles of waders in murky water, mistaking them for fish. Never fatal.",
    habitats: ["Shallow Reefs", "Sand Flats", "Mangrove Edges"],
    depthRangeM: "0 - 75m",
    diet: "Small fish, mullet, wrasses, crabs, squid",
    conservationStatus: "Near Threatened",
    conservationDetails: "Heavily affected by reef degradation and coastal development. Frequently caught in artisanal fisheries for meat and fin markets.",
    description: "A small, active shark instantly recognizable by the prominent black tips on its dorsal and caudal fins, bordered by a light band.",
    behavior: "Highly active during the day. Often found in small groups patrolling shallow reef crests, sometimes with their dorsal fins sticking out of the water.",
    coolFact: "Blacktip Reef Sharks are extremely sensitive to water changes and can adapt to live in brackish water and shallow pools that are barely deep enough to cover them.",
    sources: ["Wikipedia - Blacktip Reef Shark", "Shark Research Institute (SRI)", "WWF Coral Reef Protection"]
  },
  {
    id: "leopard-shark",
    name: "Leopard Shark",
    scientificName: "Triakis semifasciata",
    avgSizeM: 1.5,
    maxSizeM: 1.9,
    maxWeightKg: 18,
    maxSpeedKmh: 18,
    threatLevel: "Low",
    threatReason: "Completely harmless to humans. Extremely timid; they swim away immediately if approached. No attacks have ever been recorded.",
    habitats: ["Sandy Bays", "Kelp Forests", "Estuaries"],
    depthRangeM: "0 - 90m",
    diet: "Crabs, clams, shrimp, fish eggs, worms, small fish",
    conservationStatus: "Least Concern",
    conservationDetails: "Well-managed populations, especially along the California coast, which has strict size and catch limits. WWF supports sustainable coastal management.",
    description: "A striking, slender shark decorated with bold black bars and spots along its bronze-grey body, resembling a leopard's coat.",
    behavior: "Strong, undulating swimmers that form large, active schools, often mixed with dogfish and smooth-hound sharks. They feed primarily on the sea floor.",
    coolFact: "Leopard Sharks have specialized, flat teeth that act like pavements, perfect for crushing the hard shells of crabs and clams.",
    sources: ["Wikipedia - Leopard Shark", "Shark Research Institute (SRI)", "WWF USA Coastlines"]
  }
];

window.SHARK_GLOBAL_STATS = {
  totalSpecies: 512,
  totalThreatened: 150, // CR + EN + VU
  percentThreatened: "31%", // WWF status statistic
  iucnDistribution: {
    "Critically Endangered": 35,
    "Endangered": 48,
    "Vulnerable": 67,
    "Near Threatened": 85,
    "Least Concern": 137,
    "Data Deficient": 140
  }
};
